/**
 * Additional environment variables for secrets that are set via wrangler secret put
 * These are not auto-generated by wrangler types and must be maintained manually
 */
declare namespace Cloudflare {
  interface Env {
    FORCE_GOOGLE_AUTH?: string;
  }
}
