/**
 * Pre-render React Email templates to static HTML
 *
 * This script renders all email templates at build time to avoid
 * the `cache` in fetch issue that CF Workers doesn't support.
 * The rendered HTML is saved to a generated file that can be imported at runtime.
 */

import { render } from '@react-email/render';
import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
import {
  WelcomeEmail,
  NuboProEmail,
  AutoLabelingEmail,
  AIWritingAssistantEmail,
  ShortcutsEmail,
  CategoriesEmail,
  SuperSearchEmail,
  NuboProWelcomeEmail,
  NuboCancellationEmail,
  NuboWorkspaceEmail,
} from '../src/lib/react-emails/email-sequences';

// Template for generating the email templates file
const generateTemplateFile = (templates: Record<string, string>) => {
  return `/**
 * Pre-rendered email templates
 * Generated by scripts/prerender-emails.ts
 * DO NOT EDIT MANUALLY
 */

export type EmailTemplateName =
  | 'welcome'
  | 'nuboPro'
  | 'autoLabeling'
  | 'aiWritingAssistant'
  | 'shortcuts'
  | 'categories'
  | 'superSearch'
  | 'nuboProWelcome'
  | 'nuboCancellation'
  | 'nuboWorkspace';

// Pre-rendered HTML templates with {{name}} placeholder
const templates: Record<EmailTemplateName, string> = ${JSON.stringify(templates, null, 2)};

/**
 * Get a pre-rendered email template with the name replaced
 */
export function getEmailHtml(templateName: EmailTemplateName, name?: string): string {
  const template = templates[templateName];
  if (!template) {
    throw new Error(\`Unknown email template: \${templateName}\`);
  }
  // Replace the placeholder with the actual name
  return template.replace(/\\{\\{name\\}\\}/g, name || 'there');
}

/**
 * Email subjects for each template
 */
export const emailSubjects: Record<EmailTemplateName, string> = {
  welcome: 'Welcome to Nubo',
  nuboPro: 'Nubo Pro is here 🚀💼',
  autoLabeling: 'New in Nubo: Auto-labeling is here 🎉📥',
  aiWritingAssistant: 'Write faster with AI ✍️✨',
  shortcuts: 'Fly through your inbox with shortcuts ⚡️',
  categories: 'Inbox chaos? We cleaned it up for you 🧼📥',
  superSearch: 'Search your inbox like you talk 🧠🔍',
  nuboProWelcome: 'You\\'re Pro now 😎 Welcome to the fast lane',
  nuboCancellation: 'You\\'ve canceled Nubo Pro 💔',
  nuboWorkspace: 'Nubo Workspace — Your team\\'s new home 🏢✨',
};
`;
};

async function main() {
  console.log('Pre-rendering email templates...');

  // Render all templates with a placeholder name that we'll replace at runtime
  const templates: Record<string, string> = {
    welcome: await render(WelcomeEmail({ name: '{{name}}' })),
    nuboPro: await render(NuboProEmail({ name: '{{name}}' })),
    autoLabeling: await render(AutoLabelingEmail({ name: '{{name}}' })),
    aiWritingAssistant: await render(AIWritingAssistantEmail({ name: '{{name}}' })),
    shortcuts: await render(ShortcutsEmail({ name: '{{name}}' })),
    categories: await render(CategoriesEmail({ name: '{{name}}' })),
    superSearch: await render(SuperSearchEmail({ name: '{{name}}' })),
    nuboProWelcome: await render(NuboProWelcomeEmail({ name: '{{name}}' })),
    nuboCancellation: await render(NuboCancellationEmail({ name: '{{name}}' })),
    nuboWorkspace: await render(NuboWorkspaceEmail({ name: '{{name}}' })),
  };

  // Generate the output file
  const outputPath = path.join(__dirname, '../src/lib/email-templates.generated.ts');
  const content = generateTemplateFile(templates);

  fs.writeFileSync(outputPath, content, 'utf-8');
  console.log(`Generated ${outputPath}`);
  console.log('Email templates pre-rendered successfully!');
}

main().catch((error) => {
  console.error('Failed to pre-render email templates:', error);
  process.exit(1);
});
